"""
This type stub file was generated by pyright.
"""

def make_asgi_app(registry=...): # -> (scope: Unknown, receive: Unknown, send: Unknown) -> Coroutine[Any, Any, None]:
    """Create a ASGI app which serves the metrics from a registry."""
    ...

