"""
This type stub file was generated by pyright.
"""

class ExceptionCounter:
    def __init__(self, counter, exception) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, typ, value, traceback): # -> None:
        ...
    
    def __call__(self, f):
        ...
    


class InprogressTracker:
    def __init__(self, gauge) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, typ, value, traceback): # -> None:
        ...
    
    def __call__(self, f):
        ...
    


class Timer:
    def __init__(self, callback) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, typ, value, traceback): # -> None:
        ...
    
    def __call__(self, f):
        ...
    


