"""
This type stub file was generated by pyright.
"""

class GCCollector:
    """Collector for Garbage collection statistics."""
    def __init__(self, registry=...) -> None:
        ...
    
    def collect(self): # -> list[CounterMetricFamily]:
        ...
    


GC_COLLECTOR = ...
