"""
This type stub file was generated by pyright.
"""

def text_string_to_metric_families(text): # -> Generator[Metric, None, None]:
    """Parse Prometheus text format from a unicode string.

    See text_fd_to_metric_families.
    """
    ...

ESCAPE_SEQUENCES = ...
def replace_escape_sequence(match): # -> str:
    ...

HELP_ESCAPING_RE = ...
ESCAPING_RE = ...
def text_fd_to_metric_families(fd): # -> Generator[Metric, None, None]:
    """Parse Prometheus text format from a file descriptor.

    This is a laxer parser than the main Go parser,
    so successful parsing does not imply that the parsed
    text meets the specification.

    Yields Metric's.
    """
    ...

