"""
This type stub file was generated by pyright.
"""

class PlatformCollector:
    """Collector for python platform information"""
    def __init__(self, registry=..., platform=...) -> None:
        ...
    
    def collect(self): # -> list[GaugeMetricFamily]:
        ...
    


PLATFORM_COLLECTOR = ...
