"""
This type stub file was generated by pyright.
"""

class ProcessCollector:
    """Collector for Standard Exports such as cpu and memory."""
    def __init__(self, namespace=..., pid=..., proc=..., registry=...) -> None:
        ...
    
    def collect(self): # -> list[Unknown]:
        ...
    


PROCESS_COLLECTOR = ...
