"""
This type stub file was generated by pyright.
"""

class Timestamp:
    """A nanosecond-resolution timestamp."""
    def __init__(self, sec, nsec) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __float__(self): # -> float:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __gt__(self, other) -> bool:
        ...
    


Sample = ...
Exemplar = ...
