"""
This type stub file was generated by pyright.
"""

class MutexValue:
    """A float protected by a mutex."""
    _multiprocess = ...
    def __init__(self, typ, metric_name, name, labelnames, labelvalues, **kwargs) -> None:
        ...
    
    def inc(self, amount): # -> None:
        ...
    
    def set(self, value): # -> None:
        ...
    
    def set_exemplar(self, exemplar): # -> None:
        ...
    
    def get(self): # -> float:
        ...
    
    def get_exemplar(self): # -> None:
        ...
    


def MultiProcessValue(process_identifier=...): # -> Type[MmapedValue]:
    """Returns a MmapedValue class based on a process_identifier function.

    The 'process_identifier' function MUST comply with this simple rule:
    when called in simultaneously running processes it MUST return distinct values.

    Using a different function than the default 'os.getpid' is at your own risk.
    """
    class MmapedValue:
        """A float protected by a mutex backed by a per-process mmaped file."""
        ...
    
    

def get_value_class(): # -> Type[MmapedValue] | Type[MutexValue]:
    ...

ValueClass = ...
