"""
This type stub file was generated by pyright.
"""

import weakref

str = ...
def isclose(a, b, rel_tol=..., abs_tol=...): # -> bool:
    ...

def mean(data): # -> float:
    ...

def median(data):
    ...

def log2(x): # -> float:
    ...

class frozendict(Mapping):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def __getitem__(self, key):
        ...
    
    def copy(self, **add_or_replace): # -> frozendict:
        ...
    
    def __iter__(self): # -> Iterator[Unknown]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    


class WeakMethod(weakref.ref):
    """
    A custom `weakref.ref` subclass which simulates a weak reference to
    a bound method, working around the lifetime problem of bound methods.
    """
    __slots__ = ...
    def __new__(cls, meth, callback=...):
        ...
    
    def __call__(self): # -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    __hash__ = ...


