"""
This type stub file was generated by pyright.
"""

from threading import Thread

str = ...
_THREADS = ...
class GPIOThread(Thread):
    def __init__(self, group=..., target=..., name=..., args=..., kwargs=...) -> None:
        ...
    
    def start(self): # -> None:
        ...
    
    def stop(self, timeout=...): # -> None:
        ...
    
    def join(self, timeout=...): # -> None:
        ...
    


