#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing rasppi-prometheus...\n"
sudo cp rasppi-prometheus.py /usr/local/bin/
sudo chmod +x /usr/local/bin/rasppi-prometheus.py

echo "=> Starting rasppi-prometheus...\n"
sudo cp rasppi-prometheus.sh /etc/init.d/
sudo chmod +x /etc/init.d/rasppi-prometheus.sh

sudo update-rc.d rasppi-prometheus.sh defaults
sudo /etc/init.d/rasppi-prometheus.sh start

echo "rasppi-prometheus installed."
