"""
This type stub file was generated by pyright.
"""

CONTENT_TYPE_LATEST = ...
def generate_latest(registry): # -> bytes:
    '''Returns the metrics from the registry in latest text format as a string.'''
    ...

